/* Generated by Yosys 0.43 (git sha1 ead4718e5, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "counter.v:1.1-18.19" *)
module counter(clk, reset, up_down, load, data, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "counter.v:5.20-5.25" *)
  wire _22_;
  (* src = "counter.v:5.20-5.25" *)
  wire _23_;
  (* src = "counter.v:5.20-5.25" *)
  wire _24_;
  (* src = "counter.v:5.20-5.25" *)
  wire _25_;
  (* src = "counter.v:4.15-4.19" *)
  wire _26_;
  (* src = "counter.v:4.15-4.19" *)
  wire _27_;
  (* src = "counter.v:4.15-4.19" *)
  wire _28_;
  (* src = "counter.v:4.15-4.19" *)
  wire _29_;
  (* src = "counter.v:3.19-3.23" *)
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  (* src = "counter.v:3.13-3.18" *)
  wire _49_;
  (* src = "counter.v:3.24-3.31" *)
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  (* src = "counter.v:3.9-3.12" *)
  input clk;
  wire clk;
  (* src = "counter.v:5.20-5.25" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "counter.v:4.15-4.19" *)
  input [3:0] data;
  wire [3:0] data;
  (* src = "counter.v:3.19-3.23" *)
  input load;
  wire load;
  (* src = "counter.v:3.13-3.18" *)
  input reset;
  wire reset;
  (* src = "counter.v:3.24-3.31" *)
  input up_down;
  wire up_down;
  sky130_fd_sc_hd__nor2_1 _55_ (
    .A(_22_),
    .B(_30_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__a21oi_1 _56_ (
    .A1(_26_),
    .A2(_30_),
    .B1(_31_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__nor2_1 _57_ (
    .A(_49_),
    .B(_32_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__inv_1 _58_ (
    .A(_27_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__or2_2 _59_ (
    .A(_22_),
    .B(_23_),
    .X(_34_)
  );
  sky130_fd_sc_hd__nand2_1 _60_ (
    .A(_22_),
    .B(_23_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__a21o_1 _61_ (
    .A1(_34_),
    .A2(_35_),
    .B1(_50_),
    .X(_36_)
  );
  sky130_fd_sc_hd__a31oi_1 _62_ (
    .A1(_50_),
    .A2(_34_),
    .A3(_35_),
    .B1(_30_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__a221oi_1 _63_ (
    .A1(_30_),
    .A2(_33_),
    .B1(_36_),
    .B2(_37_),
    .C1(_49_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__or3_1 _64_ (
    .A(_22_),
    .B(_50_),
    .C(_23_),
    .X(_38_)
  );
  sky130_fd_sc_hd__nand3_1 _65_ (
    .A(_22_),
    .B(_50_),
    .C(_23_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__and3_1 _66_ (
    .A(_24_),
    .B(_38_),
    .C(_39_),
    .X(_40_)
  );
  sky130_fd_sc_hd__a21oi_1 _67_ (
    .A1(_38_),
    .A2(_39_),
    .B1(_24_),
    .Y(_41_)
  );
  sky130_fd_sc_hd__inv_1 _68_ (
    .A(_28_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__a21oi_1 _69_ (
    .A1(_30_),
    .A2(_42_),
    .B1(_49_),
    .Y(_43_)
  );
  sky130_fd_sc_hd__o31a_1 _70_ (
    .A1(_30_),
    .A2(_40_),
    .A3(_41_),
    .B1(_43_),
    .X(_20_)
  );
  sky130_fd_sc_hd__inv_1 _71_ (
    .A(_29_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__nand4_1 _72_ (
    .A(_22_),
    .B(_50_),
    .C(_23_),
    .D(_24_),
    .Y(_45_)
  );
  sky130_fd_sc_hd__or4_4 _73_ (
    .A(_22_),
    .B(_50_),
    .C(_23_),
    .D(_24_),
    .X(_46_)
  );
  sky130_fd_sc_hd__a21o_1 _74_ (
    .A1(_45_),
    .A2(_46_),
    .B1(_25_),
    .X(_47_)
  );
  sky130_fd_sc_hd__a31oi_1 _75_ (
    .A1(_25_),
    .A2(_45_),
    .A3(_46_),
    .B1(_30_),
    .Y(_48_)
  );
  sky130_fd_sc_hd__a221oi_1 _76_ (
    .A1(_30_),
    .A2(_44_),
    .B1(_47_),
    .B2(_48_),
    .C1(_49_),
    .Y(_21_)
  );
  (* src = "counter.v:7.3-17.6" *)
  sky130_fd_sc_hd__dfxtp_1 _77_ (
    .CLK(clk),
    .D(_51_),
    .Q(count[0])
  );
  (* src = "counter.v:7.3-17.6" *)
  sky130_fd_sc_hd__dfxtp_1 _78_ (
    .CLK(clk),
    .D(_52_),
    .Q(count[1])
  );
  (* src = "counter.v:7.3-17.6" *)
  sky130_fd_sc_hd__dfxtp_1 _79_ (
    .CLK(clk),
    .D(_53_),
    .Q(count[2])
  );
  (* src = "counter.v:7.3-17.6" *)
  sky130_fd_sc_hd__dfxtp_1 _80_ (
    .CLK(clk),
    .D(_54_),
    .Q(count[3])
  );
  assign _22_ = count[0];
  assign _26_ = data[0];
  assign _30_ = load;
  assign _50_ = up_down;
  assign _23_ = count[1];
  assign _27_ = data[1];
  assign _24_ = count[2];
  assign _28_ = data[2];
  assign _25_ = count[3];
  assign _29_ = data[3];
  assign _49_ = reset;
  assign _51_ = _18_;
  assign _52_ = _19_;
  assign _53_ = _20_;
  assign _54_ = _21_;
endmodule
